### ISSUE TITLE
Manage nginx.conf with SaltStack

### ISSUE THREAD

**Issue by Oodnadatta** [REGOVAR/ServerConfiguration#11]
Error in Salt because we watch /etc/nginx/nginx.conf whereas /etc/nginx/nginx.conf is not managed with salt yet.

ERROR:
```
          ID: nginx
    Function: service.running
      Result: False
     Comment: The following requisites were not found:
                                 watch:
                                     file: /etc/nginx/nginx.conf
```
